### ISSUE TITLE
VAN Connector

### ISSUE THREAD

**Issue by jburchard** [move-coop/parsons#15]
The VAN connector works, but it was the first one that we built and needs some love.

- [x] Create scaffolding for standardized APIConnector class
- [x] Create API `GET` methods that paginate
- [x] Refactor all relevant VAN methods to use the new `GET` method.
- [x] Create API `POST` method.
- [x] Refactor all relevant VAN methods to use the new `POST` method.
- [x] Create API `DELETE` methods.
- [x] Refactor all relevant VAN methods to use the new `DELETE` method.
- [x] Create API `PATCH` methods.
- [x] Refactor all relevant VAN methods to use the new `PATCH` method.
