### ISSUE TITLE
Validation epic

### ISSUE THREAD

**Issue by neverett** [move-coop/parsons#591]
This is a parent issue to track validation-related issues:
- [ ] [Phone number validation](https://github.com/move-coop/parsons/issues/28)
- [ ] [Email validation](https://github.com/move-coop/parsons/issues/91)
- [ ] [Address validation](https://github.com/move-coop/parsons/issues/483)

**Comment by shaunagm** [comment]
Closing this because we're not using the epic pattern anymore, but the individual issue remains open.
