### ISSUE TITLE
Redshift improvements and bug fixes epic

### ISSUE THREAD

**Issue by neverett** [move-coop/parsons#593]
Gathering Redshift issues here so we can group / tackle them together when it makes sense to.

## Improvements

- [ ] [Merge Redshift and PostgresCore](https://github.com/move-coop/parsons/issues/190)
- [ ] [alter_varchar_column_widths() - compare 2 redshift tables](https://github.com/move-coop/parsons/issues/128)
- [ ] [Create Upsert Method that is Redshift to Redshift](https://github.com/move-coop/parsons/issues/253)
- [ ] [Redshift: Add DIST/SORT keys to upsert.](https://github.com/move-coop/parsons/issues/194)
- [ ] [Convenience Function to get Distkey & Sortkey](https://github.com/move-coop/parsons/issues/364)
- [ ] [Deduplicate records in staging on upsert](https://github.com/move-coop/parsons/issues/355)
- [ ] [Redshift get_table_definition method based on non-standard Redshift views](https://github.com/move-coop/parsons/issues/301)

## Bug fixes

- [ ] [Redshift populate_table_from_query silent error](https://github.com/move-coop/parsons/issues/343)
- [ ] [Redshift: Add tag to temp file used to copy into Redshift](https://github.com/move-coop/parsons/issues/371)
- [ ] [Redshift Connector not working in Python 3.6](https://github.com/move-coop/parsons/issues/518)
- [ ] [Fixing Specifycols in Redshift Copy S3](https://github.com/move-coop/parsons/issues/457)
- [ ] [rs.upsert alter_table not working](https://github.com/move-coop/parsons/issues/493)
- [ ] [RS Upsert Vacuum Error](https://github.com/move-coop/parsons/issues/401)
- [ ] [populate_table_from_query - doesn't cascade](https://github.com/move-coop/parsons/issues/311)

**Comment by shaunagm** [comment]
Closing this because we're not using the epic pattern anymore, but the individual issues remain open.
